[Service]
    flush        1
    log_level    info
    daemon       off
    http_server  true
    http_listen  0.0.0.0
    http_port    2020

    # Important production settings:
    storage.path            /fluent-bit/buffers
    storage.sync            normal
    storage.checksum        off
    storage.backlog.mem_limit 100MB

[Input]
    name         forward
    listen       0.0.0.0
    port         24224
    buffer_chunk_size  1M
    buffer_max_size    5M

[Output]
    name         loki
    match        *
    url          ${LOKI_URL}
    labels       job=fluentbit,container=${tag}
    auto_kubernetes_labels false

    # Output reliability
    tls.verify          off
    retry_limit         30
    storage.total_limit_size 500MB
