#!/bin/bash
# ============================================================
# Script: tf-localstack-override.sh
# Purpose: Write/remove Terraform *_override.tf files that point basis's three Terraform layers
#          (terraform/state, terraform/envs/shared, terraform/envs/dev) at LocalStack instead of
#          real AWS, for the local CI/CD provisioning emulation harness (sh/local-ci/*).
# Usage:
#   bash ./sh/local-ci/tf-localstack-override.sh -m write|clean [-e <endpoint-url>]
# Examples:
#   bash ./sh/local-ci/tf-localstack-override.sh -m write
#   bash ./sh/local-ci/tf-localstack-override.sh -m write -e http://localhost:4566
#   bash ./sh/local-ci/tf-localstack-override.sh -m clean
# Description:
#   Terraform natively merges `*_override.tf` into a configuration (kit-modules/basis/.gitignore
#   already ignores `override.tf`, `override.tf.json`, `*_override.tf`, `*_override.tf.json`), so
#   this generator never touches a tracked basis file. `write` drops `localstack_override.tf`
#   into terraform/state, terraform/envs/shared and terraform/envs/dev; `clean` removes exactly
#   those three files and nothing else. Called by sh/local-ci/harness-up.sh (write) and
#   sh/local-ci/harness-down.sh (clean) — see the plan's contract 4.
# ============================================================

# Stop on errors, unset vars, and fail pipelines; preserve ERR traps
set -Eeuo pipefail

# Resolve project root (this script is at: sh/local-ci/tf-localstack-override.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../" && pwd)"

# Colors
# shellcheck source=/dev/null
source "$PROJECT_ROOT/sh/utils/colors.sh"

BASIS_TERRAFORM_DIR="$PROJECT_ROOT/kit-modules/basis/terraform"
OVERRIDE_FILENAME="localstack_override.tf"

# Layers this script writes/cleans, and whether each carries an s3 backend override.
LAYER_DIRS=(
    "$BASIS_TERRAFORM_DIR/state"
    "$BASIS_TERRAFORM_DIR/envs/shared"
    "$BASIS_TERRAFORM_DIR/envs/dev"
)

MODE=""
ENDPOINT_URL="http://localstack:4566"

usage() {
    echo "Usage: bash ./sh/local-ci/tf-localstack-override.sh -m write|clean [-e <endpoint-url>]"
    echo "  -m  required: write|clean"
    echo "  -e  optional: LocalStack endpoint URL (default: http://localstack:4566)"
    echo ""
    echo "Examples:"
    echo "  bash ./sh/local-ci/tf-localstack-override.sh -m write"
    echo "  bash ./sh/local-ci/tf-localstack-override.sh -m write -e http://localhost:4566"
    echo "  bash ./sh/local-ci/tf-localstack-override.sh -m clean"
}

while getopts ":m:e:h" opt; do
    case $opt in
        m)
            MODE="$OPTARG"
            ;;
        e)
            ENDPOINT_URL="$OPTARG"
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
            echo -e "${LIGHTRED}[Error]${RESET} Invalid option: -$OPTARG"; exit 1;
            ;;
        :)
            echo -e "${LIGHTRED}[Error]${RESET} Option -$OPTARG requires an argument"; exit 1;
            ;;
    esac
done

if [ "$MODE" != "write" ] && [ "$MODE" != "clean" ]; then
    echo -e "${LIGHTRED}[Error]${RESET} -m is required and must be 'write' or 'clean'"
    usage
    exit 1
fi

# Refuse to run if any target directory is missing — never partially write/clean.
for dir in "${LAYER_DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        echo -e "${LIGHTRED}[Error]${RESET} Target directory not found: $dir"
        echo -e "${LIGHTRED}[Error]${RESET} kit-modules/basis is missing or its terraform layout changed. Refusing to run."
        exit 1
    fi
done

write_provider_block() {
    cat <<EOF
# LOCAL EMULATION HARNESS ONLY — generated by sh/local-ci/tf-localstack-override.sh — do not commit
# Terraform natively merges *_override.tf files; this never edits a tracked basis file
# (kit-modules/basis/.gitignore already ignores *_override.tf).

provider "aws" {
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  access_key                  = "test"
  secret_key                  = "test"

  endpoints {
    s3       = "$ENDPOINT_URL"
    dynamodb = "$ENDPOINT_URL"
    ec2      = "$ENDPOINT_URL"
    sts      = "$ENDPOINT_URL"
  }
}
EOF
}

write_backend_block() {
    cat <<EOF

terraform {
  backend "s3" {
    endpoints = {
      s3       = "$ENDPOINT_URL"
      dynamodb = "$ENDPOINT_URL"
      sts      = "$ENDPOINT_URL"
    }
    use_path_style              = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    access_key                  = "test"
    secret_key                  = "test"
  }
}
EOF
}

write_remote_state_override() {
    # Overrides envs/dev/main.tf's `data "terraform_remote_state" "shared"` block. Terraform's
    # override merge replaces the WHOLE `config` map when it is re-declared (no deep-merge of map
    # attributes), so every key from the original block (bucket/key/region) must be repeated here
    # alongside the LocalStack-only additions — read from kit-modules/basis/terraform/envs/dev/main.tf
    # before changing this.
    cat <<EOF

data "terraform_remote_state" "shared" {
  backend = "s3"
  config = {
    bucket = var.tf_backend_bucket
    key    = "envs/shared/network.tfstate"
    region = var.aws_region

    endpoints = {
      s3       = "$ENDPOINT_URL"
      dynamodb = "$ENDPOINT_URL"
      sts      = "$ENDPOINT_URL"
    }
    use_path_style              = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    access_key                  = "test"
    secret_key                  = "test"
  }
}
EOF
}

do_write() {
    local state_dir="$BASIS_TERRAFORM_DIR/state"
    local shared_dir="$BASIS_TERRAFORM_DIR/envs/shared"
    local dev_dir="$BASIS_TERRAFORM_DIR/envs/dev"

    # terraform/state has no backend.tf (local state) — provider override only.
    write_provider_block > "$state_dir/$OVERRIDE_FILENAME"
    echo -e "${LIGHTGREEN}[Info]${RESET} Wrote $state_dir/$OVERRIDE_FILENAME"

    # terraform/envs/shared uses an s3 backend — provider + backend override.
    {
        write_provider_block
        write_backend_block
    } > "$shared_dir/$OVERRIDE_FILENAME"
    echo -e "${LIGHTGREEN}[Info]${RESET} Wrote $shared_dir/$OVERRIDE_FILENAME"

    # terraform/envs/dev uses an s3 backend AND reads shared's state via terraform_remote_state —
    # provider + backend + remote-state override.
    {
        write_provider_block
        write_backend_block
        write_remote_state_override
    } > "$dev_dir/$OVERRIDE_FILENAME"
    echo -e "${LIGHTGREEN}[Info]${RESET} Wrote $dev_dir/$OVERRIDE_FILENAME"

    echo -e "${LIGHTGREEN}[Success]${RESET} LocalStack Terraform overrides written (endpoint: $ENDPOINT_URL)"
}

do_clean() {
    local removed=0
    for dir in "${LAYER_DIRS[@]}"; do
        local target="$dir/$OVERRIDE_FILENAME"
        if [ -f "$target" ]; then
            rm -f "$target"
            echo -e "${LIGHTGREEN}[Info]${RESET} Removed $target"
            removed=$((removed + 1))
        else
            echo -e "${CYAN}[Info]${RESET} Nothing to remove at $target"
        fi
    done
    echo -e "${LIGHTGREEN}[Success]${RESET} LocalStack Terraform overrides cleaned ($removed file(s) removed)"
}

case "$MODE" in
    write)
        do_write
        ;;
    clean)
        do_clean
        ;;
esac
