#!/bin/bash
# ============================================================
# Script: tf-localstack-override.sh
# Purpose: Write/remove the Terraform *_override.tf file that points basis's `state` layer
#          (terraform/state — the one layer deliberately kept outside the Terragrunt graph, see
#          terraform/root.hcl's header) at LocalStack instead of real AWS, for the local CI/CD
#          provisioning emulation harness (sh/local-ci/*).
# Usage:
#   bash ./sh/local-ci/tf-localstack-override.sh -m write|clean [-e <endpoint-url>]
# Examples:
#   bash ./sh/local-ci/tf-localstack-override.sh -m write
#   bash ./sh/local-ci/tf-localstack-override.sh -m write -e http://localhost:4566
#   bash ./sh/local-ci/tf-localstack-override.sh -m clean
# Description:
#   Terraform natively merges `*_override.tf` into a configuration (kit-modules/basis/.gitignore
#   already ignores `override.tf`, `override.tf.json`, `*_override.tf`, `*_override.tf.json`), so
#   this generator never touches a tracked basis file. `write` drops `localstack_override.tf`
#   into terraform/state; `clean` removes exactly that file. Called by sh/local-ci/harness-up.sh
#   (write) and sh/local-ci/harness-down.sh (clean).
#
#   Every other layer (terraform/envs/*) is now Terragrunt-managed — those get their LocalStack
#   endpoints from terraform/root.hcl's own `local.localstack_endpoint` conditional instead (gated
#   on the LOCALCI_LOCALSTACK_ENDPOINT env var, which harness-up.sh writes into
#   config/environment/.env.type.dev.override), not from an override.tf file here. An override.tf
#   redeclaring `terraform { backend "s3" {} }` or `provider "aws" {}` in one of those directories
#   would collide with Terragrunt's own generated backend_generated.tf/provider_generated.tf —
#   Terraform rejects duplicate backend/provider blocks outright.
# ============================================================

# Stop on errors, unset vars, and fail pipelines; preserve ERR traps
set -Eeuo pipefail

# Resolve project root (this script is at: sh/local-ci/tf-localstack-override.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../" && pwd)"

# Colors
# shellcheck source=/dev/null
source "$PROJECT_ROOT/sh/utils/colors.sh"

BASIS_TERRAFORM_DIR="$PROJECT_ROOT/kit-modules/basis/terraform"
OVERRIDE_FILENAME="localstack_override.tf"

# Layers this script writes/cleans. Only `state` — see the header comment for why the
# Terragrunt-managed envs/* layers are handled by root.hcl instead.
LAYER_DIRS=(
    "$BASIS_TERRAFORM_DIR/state"
)

MODE=""
ENDPOINT_URL="http://localstack:4566"

usage() {
    echo "Usage: bash ./sh/local-ci/tf-localstack-override.sh -m write|clean [-e <endpoint-url>]"
    echo "  -m  required: write|clean"
    echo "  -e  optional: LocalStack endpoint URL (default: http://localstack:4566)"
    echo ""
    echo "Examples:"
    echo "  bash ./sh/local-ci/tf-localstack-override.sh -m write"
    echo "  bash ./sh/local-ci/tf-localstack-override.sh -m write -e http://localhost:4566"
    echo "  bash ./sh/local-ci/tf-localstack-override.sh -m clean"
}

while getopts ":m:e:h" opt; do
    case $opt in
        m)
            MODE="$OPTARG"
            ;;
        e)
            ENDPOINT_URL="$OPTARG"
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
            echo -e "${LIGHTRED}[Error]${RESET} Invalid option: -$OPTARG"; exit 1;
            ;;
        :)
            echo -e "${LIGHTRED}[Error]${RESET} Option -$OPTARG requires an argument"; exit 1;
            ;;
    esac
done

if [ "$MODE" != "write" ] && [ "$MODE" != "clean" ]; then
    echo -e "${LIGHTRED}[Error]${RESET} -m is required and must be 'write' or 'clean'"
    usage
    exit 1
fi

# Refuse to run if any target directory is missing — never partially write/clean.
for dir in "${LAYER_DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        echo -e "${LIGHTRED}[Error]${RESET} Target directory not found: $dir"
        echo -e "${LIGHTRED}[Error]${RESET} kit-modules/basis is missing or its terraform layout changed. Refusing to run."
        exit 1
    fi
done

write_provider_block() {
    cat <<EOF
# LOCAL EMULATION HARNESS ONLY — generated by sh/local-ci/tf-localstack-override.sh — do not commit
# Terraform natively merges *_override.tf files; this never edits a tracked basis file
# (kit-modules/basis/.gitignore already ignores *_override.tf).

provider "aws" {
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  access_key                  = "test"
  secret_key                  = "test"

  endpoints {
    s3       = "$ENDPOINT_URL"
    dynamodb = "$ENDPOINT_URL"
    ec2      = "$ENDPOINT_URL"
    sts      = "$ENDPOINT_URL"
  }
}
EOF
}

write_backend_block() {
    # $1: the layer's state-file key, copied verbatim from its tracked backend.tf. Terraform's
    # override merge for a `terraform { backend "s3" {} }` block was found (empirically, running
    # `terraform init` for real against this override — a static `-backend=false` validate pass
    # does NOT catch this) to require every attribute to be restated, not just the ones being
    # added: omitting `key` here left it unset after merge, and `terraform init` fell back to an
    # interactive prompt for it (fatal on a non-interactive CI runner). Restating `key` and
    # `encrypt` from the original per-layer backend.tf avoids that. See sh/local-ci/EVIDENCE.md.
    local state_key="$1"
    cat <<EOF

terraform {
  backend "s3" {
    key     = "$state_key"
    encrypt = true

    endpoints = {
      s3       = "$ENDPOINT_URL"
      dynamodb = "$ENDPOINT_URL"
      sts      = "$ENDPOINT_URL"
    }
    use_path_style              = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    access_key                  = "test"
    secret_key                  = "test"
  }
}
EOF
}

do_write() {
    local state_dir="$BASIS_TERRAFORM_DIR/state"

    # terraform/state uses an s3 backend — provider + backend override.
    # key copied verbatim from state/backend.tf.
    {
        write_provider_block
        write_backend_block "state/terraform.tfstate"
    } > "$state_dir/$OVERRIDE_FILENAME"
    echo -e "${LIGHTGREEN}[Info]${RESET} Wrote $state_dir/$OVERRIDE_FILENAME"

    echo -e "${LIGHTGREEN}[Success]${RESET} LocalStack Terraform overrides written (endpoint: $ENDPOINT_URL)"
}

do_clean() {
    local removed=0
    for dir in "${LAYER_DIRS[@]}"; do
        local target="$dir/$OVERRIDE_FILENAME"
        if [ -f "$target" ]; then
            rm -f "$target"
            echo -e "${LIGHTGREEN}[Info]${RESET} Removed $target"
            removed=$((removed + 1))
        else
            echo -e "${CYAN}[Info]${RESET} Nothing to remove at $target"
        fi
    done
    echo -e "${LIGHTGREEN}[Success]${RESET} LocalStack Terraform overrides cleaned ($removed file(s) removed)"
}

case "$MODE" in
    write)
        do_write
        ;;
    clean)
        do_clean
        ;;
esac
