version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./public:/var/www/html
      - ./logs/nginx:/var/log/nginx
    expose:
      - 8080
    restart: always
    links:
      - wordpress
    environment:
      VIRTUAL_HOST: mealdeliveryservices.lc
      VIRTUAL_PORT: 8080

  wordpress:
    image: wordpress:5.7.2-php7.3-fpm
    container_name: wordpress
    restart: unless-stopped
    links:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./public:/var/www/html


  mysql:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: PASSWORD
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: PASSWORD
volumes:
    db_data:
networks:
  default:
    external:
      name: nginx-proxy