version: "3.9"

networks:
  default:
    external:
      name: nginx-proxy


services:

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD


  wordpress:
    image: wordpress:5.7.2-php7.3-fpm
    container_name: wordpress
    restart: unless-stopped
    links:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html/
      - ./wp-content:/var/www/html/wp-content/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content/
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    links:
      - wordpress


volumes:
  db_data:
  wordpress: