version: "3.9"

networks:
  default:
    external:
      #external network for local development with nginx-proxy container
      name: nginx-proxy


services:

  mysql:
    image: mysql:5.7
    container_name: mealdeliveryservices_database
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      # should be .env files for all environments
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD

  wordpress:
    image: wordpress:5.7.2-php7.4-fpm
    container_name: mealdeliveryservices_wordpress
    restart: unless-stopped
    links:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./web/wordpress-core:/var/www/html # wordpress root folder for development only
      #- wordpress_core:/var/www/html # wordpress root folder volume for production
      - ./web/app:/var/www/html/wp-content # all needed wp-content folders, uploads should be in .gitignore

  nginx:
    image: nginx:1.21.0
    container_name: mealdeliveryservices_nginx
    restart: unless-stopped
    links:
      - mysql
      - wordpress
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./web/wordpress-core:/var/www/html # wordpress root folder for development only
      #- wordpress_core:/var/www/html # wordpress root folder volume for production
      - ./web/app:/var/www/html/wp-content # all needed wp-content folders, uploads should be in .gitignore


volumes:
  db_data:
  wordpress_core: