version: "3.9"


services:

  mysql:
    image: mariadb:10.5
    container_name: mealdeliveryservices_database
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    environment:
      # should be .env files for all environments
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:5.7.2-php7.4-fpm-alpine
    container_name: mealdeliveryservices_wordpress
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./web/wordpress-core:/var/www/html # wordpress root folder for development only
      #- wordpress_core:/var/www/html # wordpress root folder volume for production
      - ./web/app:/var/www/html/wp-content # all needed wp-content folders, uploads should be in .gitignore

  nginx:
    image: nginx:1.20-alpine
    container_name: mealdeliveryservices_nginx
    restart: unless-stopped
    links:
      - wordpress
    depends_on:
      - mysql
      - wordpress
    env_file: .env
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./web/wordpress-core:/var/www/html # wordpress root folder for development only
      #- wordpress_core:/var/www/html # wordpress root folder volume for production
      - ./web/app:/var/www/html/wp-content # all needed wp-content folders, uploads should be in .gitignore


volumes:
  db_data:
  #wordpress_core: