version: "3.9"


services:

  database:
    image: mariadb:10.5
    restart: unless-stopped
    env_file: .env
    # Open port only for the host. Need for SSH tunnel to connect to database from SQL Manager like HeidiSQL
    # Uncomment ports directive for using SSH tunnel, amd uncomment SSH_TUNNEL_EXT_PORT var in .env file
    #ports:
    #  - 127.0.0.1:${SSH_TUNNEL_EXT_PORT}:3306
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./docker/wordpress
    restart: unless-stopped
    links:
      - database
    depends_on:
      - database
    env_file: .env
    environment:
      # Database
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      # Site URL
      APP_PROTOCOL: ${APP_PROTOCOL}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_PORT: ${APP_PORT}
      # Environment type
      WORDPRESS_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE}
      # Debugging
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_DEBUG_DISPLAY: ${WP_DEBUG_DISPLAY}
      WORDPRESS_DEBUG_LOG: ${WP_DEBUG_LOG}
      # Memory
      WORDPRESS_MEMORY_LIMIT: ${WP_MEMORY_LIMIT}
      WORDPRESS_MAX_MEMORY_LIMIT: ${WP_MAX_MEMORY_LIMIT}
      # Cron
      WORDPRESS_DISABLE_WP_CRON: ${DISABLE_WP_CRON}
      # Redis
      WORDPRESS_REDIS_HOST: ${WP_REDIS_HOST}
      WORDPRESS_REDIS_PORT: ${WP_REDIS_PORT}
      WORDPRESS_REDIS_PREFIX: ${WP_REDIS_PREFIX}
      WORDPRESS_REDIS_MAXTTL: ${WP_REDIS_MAXTTL}

    volumes:
      - ./web/wordpress-core:/var/www/html # wordpress root folder for development only
      #- wordpress_core:/var/www/html # wordpress root folder volume for production
      - ./web/app:/var/www/html/wp-content # all needed wp-content folders, uploads should be in .gitignore
      - ./logs/wordpress:/var/log/wordpress
      # Cron
      - ./config/crontabs:/etc/crontabs
      - ./logs/cron:/var/log/cron

  nginx:
    image: nginx:1.20-alpine
    restart: unless-stopped
    links:
      - wordpress
    depends_on:
      - database
      - wordpress
    env_file: .env
    environment:
      NGINX_HOST: ${APP_DOMAIN}
      NGINX_PORT: ${APP_PORT}
    command: /bin/sh -c "envsubst '$$NGINX_HOST, $$NGINX_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./web/wordpress-core:/var/www/html # wordpress root folder for development only
      #- wordpress_core:/var/www/html # wordpress root folder volume for production
      - ./web/app:/var/www/html/wp-content # all needed wp-content folders, uploads should be in .gitignore

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped

volumes:
  db_data:
  #wordpress_core: