services:

  composer:
    image: "${APP_COMPOSER_IMAGE}"
    container_name: "${APP_NAME}-composer"
    restart: no
    env_file: .env.runtime
    environment:
      DEFAULT_USER: ${DEFAULT_USER}
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
      COMPOSER_AUTH: ${COMPOSER_AUTH:-}
    working_dir: /srv
    volumes:
      - ./:/srv
      - ./logs/wordpress:/var/log/wordpress
      - ./config/php:/usr/local/etc/php
      - ./sh:/shell:ro

  node:
    image: "${APP_NODE_IMAGE}"
    container_name: "${APP_NAME}-node"
    restart: no
    env_file: .env.runtime
    environment:
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
    working_dir: /srv/web
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./web/wp-core:/srv/web
      - ./web/wp-content:/srv/web/wp-content

  phpmyadmin:
    image: "${APP_PHPMYADMIN_IMAGE}"
    container_name: "${APP_NAME}-phpmyadmin"
    restart: no
    ports:
      - ${PMA_EXT_PORT}:80
    env_file: .env.runtime
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M

  certbot:
    image: "${APP_CERTBOT_IMAGE}"
    container_name: "${APP_NAME}-certbot"
    restart: no
    env_file: .env.runtime
    environment:
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
    volumes:
      - ./config/ssl:/etc/letsencrypt
      - ./config/certbot/cli.ini:/etc/letsencrypt/cli.ini
      - ./web/wp-core:/srv/web
      - ./logs/letsencrypt:/var/log/letsencrypt

  mailhog:
    image: "${APP_MAILHOG_IMAGE}"
    container_name: "${APP_NAME}-mailhog"
    restart: no
    ports:
      - "8025:8025"
      - "1025:1025"

  iac:
    image: "${APP_IAC_IMAGE}"
    container_name: "${APP_NAME}-iac"
    restart: no
    env_file: .env.runtime
    environment:
      DEFAULT_USER: ${DEFAULT_USER}
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
      TF_VAR_app_domain: ${APP_DOMAIN}
    working_dir: /srv
    volumes:
      - ./:/srv

networks:
  project_network:
    driver: bridge
    external: true
