services:

  composer:
    image: "${APP_COMPOSER_IMAGE}"
    container_name: "${APP_NAME}-composer"
    restart: no
    env_file: .env.runtime
    environment:
      DEFAULT_USER: ${DEFAULT_USER}
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
      COMPOSER_AUTH: ${COMPOSER_AUTH:-}
    working_dir: /srv
    volumes:
      # Project files with same path
      - ./:/srv
      # Debug log
      - ./logs/wordpress:/var/log/wordpress
      # PHP ini config
      - ./config/php:/usr/local/etc/php
      # Share shell scripts
      - ./sh:/shell:ro

  node:
    image: "${APP_NODE_IMAGE}"
    container_name: "${APP_NAME}-node"
    restart: no
    env_file: .env.runtime
    environment:
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
    working_dir: /srv/web
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      # Web root folder
      - ./web/wp-core:/srv/web
      # WordPress wp-content folder
      - ./web/wp-content:/srv/web/wp-content

  phpmyadmin:
    image: "${APP_PHPMYADMIN_IMAGE}"
    container_name: "${APP_NAME}-phpmyadmin"
    restart: no
    ports:
      - ${PMA_EXT_PORT}:80
    env_file: .env.runtime
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M

  certbot:
    image: "${APP_CERTBOT_IMAGE}"
    container_name: "${APP_NAME}-certbot"
    restart: no
    env_file: .env.runtime
    environment:
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
    volumes:
      # SSL certificate files
      - ./config/ssl:/etc/letsencrypt
      - ./config/certbot/cli.ini:/etc/letsencrypt/cli.ini
      # Web root folder
      - ./web/wp-core:/srv/web
      # Logs folder
      - ./logs/letsencrypt:/var/log/letsencrypt

  mailhog:
    image: "${APP_MAILHOG_IMAGE}"
    container_name: "${APP_NAME}-mailhog"
    restart: no
    ports:
      - "8025:8025"
      - "1025:1025"

  iac:
    image: "${APP_IAC_IMAGE}"
    container_name: "${APP_NAME}-iac"
    restart: no
    env_file: .env.runtime
    environment:
      DEFAULT_USER: ${DEFAULT_USER}
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
      TF_VAR_app_domain: ${APP_DOMAIN}
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}
      # Pass AWS credentials to the container
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${TF_VAR_aws_region}
    working_dir: /srv
    volumes:
      - ./:/srv
      - ${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:ro

networks:
  project_network:
    driver: bridge
    external: true
