version: "3.9"

services:
  phpmyadmin:
    image: phpmyadmin:5.1-apache
    restart: unless-stopped
    ports:
      - ${PMA_EXT_PORT}:80
    env_file: .env
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M