version: "3.9"

services:

  php-composer:
    image: "${APP_PHP_COMPOSER_IMAGE}"
    container_name: "${APP_NAME}_php_composer"
    restart: "no"
    env_file: .env
    environment:
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
    working_dir: /srv
    volumes:
      # Project files with same path
      - ./:/srv
      # SSMTP config
      - ./config/ssmtp:/etc/ssmtp/templates:ro
      # User added in Dockerfile
      - ~/.ssh:/home/www-data/.ssh:ro

  node:
    image: "${APP_NODE_IMAGE}"
    container_name: "${APP_NAME}_node"
    restart: "no"
    env_file: .env
    environment:
      CURRENT_UID: ${CURRENT_UID:-$DEFAULT_UID}
      CURRENT_GID: ${CURRENT_GID:-$DEFAULT_GID}
    working_dir: /srv/web
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      # Web root folder
      - ./web/wp-core:/srv/web
      # WordPress wp-content folder
      - ./web/wp-content:/srv/web/wp-content

  phpmyadmin:
    image: "${APP_PHPMYADMIN_IMAGE}"
    container_name: "${APP_NAME}_phpmyadmin"
    restart: "no"
    ports:
      - ${PMA_EXT_PORT}:80
    env_file: .env
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 500M

networks:
  project_network:
    external: true
