version: "3.9"

networks:
  default:
    external:
      #external network for local development with nginx-proxy container
      name: nginx-proxy


services:
  nginx:
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: ${APP_DOMAIN}
      VIRTUAL_PORT: 8080
