# Update sshd_config

    - name: Backup existing sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: true
      register: backup_status

    - name: Update sshd_config with new configuration
      template:
        src: ../ssh/sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: '0644'

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      when: backup_status is succeeded

