# Prepare common tasks

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required system packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - ca-certificates
          - curl
          - gnupg
          - make
          - rsync

    - name: Ensure ansible_user owns the deploy folder
      file:
        path: /srv
        owner: "{{ ansible_user }}"
        state: directory
        recurse: yes

    - name: Update hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Update PS1 to show full hostname
      replace:
        path: /home/{{ ansible_user }}/.bashrc
        regexp: '\\u@\\h'
        replace: '\\u@\\H'
        backup: yes
