all:
  children:
    development:
      hosts:
        develop.starter-kit.io:
          os: debian
          ansible_user: admin
          swap_vars:
            size: 2G
            swappiness: 20

    production:
      hosts:
        starter-kit.io:
          os: debian
          ansible_user: admin
          swap_vars:
            size: 2G
            swappiness: 20
