- name: Install required packages and settings on Debian/Ubuntu Server
  hosts:
    - development2
  become: yes
  tasks:
    - import_tasks: ./partials/common-tasks.yml
    - import_tasks: ./partials/install-docker.yml
    - import_tasks: ./partials/setup-swap.yml
