- name: Install required packages and settings on Debian/Ubuntu Server
  hosts:
    - development
    - staging
    - production
  become: yes
  tasks:
    - name: Include all tasks from partials in sorted order
      include_tasks: "{{ item }}"
      loop: "{{ lookup('fileglob', playbook_dir + '/partials/*.yml', wantlist=True) | sort }}"
      loop_control:
        label: "{{ item | basename }}"
