name: Deploy

on:
  push:
    branches:
      - feature/deploy

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir -p "$HOME/.ssh"
      - run: echo "${{ secrets.DEMO_DEPLOY_KEY }}" > "$HOME/.ssh/demo_deploy_key"
      - run: chmod 600 "$HOME/.ssh/demo_deploy_key"
      # Add Known Hosts
      - run: ssh-keyscan -H ${{ secrets.DEMO_HOST }} >> "$HOME/.ssh/known_hosts"
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/demo_deploy_key" --archive --compress --delete . ${{ secrets.DEMO_SSH_USER }}@demo.starter-kit.io:public_html/demo_deploy/
      