name: Deploy

on:
  push:
    branches:
      - feature/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{SECRETS.DEMO_DEPLOY_KEY}}" > "$HOME/.ssh/demo_deploy_key"
      - run: chmod 600 "$HOME/.ssh/demo_deploy_key"
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/demo_deploy_key -o StrictHostKeyChecking=no" --archive --compress --delete . demo@demo.starter-kit.io:public_html/demo_deploy/