name: job-deploy

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      SSH_CONFIG:
        required: true
    inputs:
      SSH_HOST_ALIAS:
        required: true
        type: string
      DEPLOY_PATH_DESTINATION:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
      ENVIRONMENT_TYPE:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare .env
        run: |
          bash ./sh/env/secret-gen.sh
          bash ./sh/env/init.sh ${{ inputs.ENVIRONMENT_TYPE }}

      - name: Install Composer and Node Dependencies
        run: |
          source ./.env
          export CURRENT_UID=$(id -u)
          export CURRENT_GID=$(id -g)
          export COMPOSER_AUTH='{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN }}"}}'
          bash ./sh/install.sh yes

      - name: Save Built cache
        uses: actions/cache@v4
        with:
          path: .
          key: build-cache-${{ github.run_number }}

  deploy:
    runs-on: ubuntu-22.04

    needs: [ build ]

    steps:
      - name: Use Built cache
        uses: actions/cache@v4
        with:
          path: .
          key: build-cache-${{ github.run_number }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo '${{ secrets.SSH_CONFIG }}' > ~/.ssh/config

      - name: Deploy via SSH
        run: |
          echo "Deploying to ${{ inputs.DEPLOY_PATH_DESTINATION }}"
          ssh ${{ inputs.SSH_HOST_ALIAS }} mkdir -p ${{ inputs.DEPLOY_PATH_DESTINATION }}
          rsync -og \
            --chmod=Dug=rwx,Fug=rw \
            --checksum \
            --recursive \
            --verbose \
            --compress \
            --links \
            --delete-after \
            --exclude ".git*" \
            --exclude "*/node_modules/" \
            --exclude "backups/" \
            --exclude "db-data/" \
            --exclude "logs/*" \
            --exclude "iac/" \
            --exclude ".env" \
            --exclude ".env.*override" \
            --exclude ".env.*secret" \
            --exclude "config/ssl/**/*.pem" \
            --exclude "web/wp-content/languages" \
            --exclude "web/wp-content/uploads" \
            --include "web/wp-content/cache" \
            ./ ${{ inputs.SSH_HOST_ALIAS }}:${{ inputs.DEPLOY_PATH_DESTINATION }}
          ssh ${{ inputs.SSH_HOST_ALIAS }} " \
            cd ${{ inputs.DEPLOY_PATH_DESTINATION }} && \
            make secret && \
            make recreate ${{ inputs.ENVIRONMENT_TYPE }}"
