name: job-deploy

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      SSH_CONFIG:
        required: true
      COMPOSER_AUTH:
        required: true
    inputs:
      SSH_HOST_ALIAS:
        required: true
        type: string
      DEPLOY_PATH_DESTINATION:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
      ENVIRONMENT_TYPE:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies - restore
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor
          key: build-cache-${{ inputs.SSH_HOST_ALIAS }}-${{ runner.os }}

      - name: Prepare .env
        run: |
          bash ./sh/env/secret-gen.sh
          echo "COMPOSER_AUTH=${{ secrets.COMPOSER_AUTH }}" >> ./config/environment/.env.secret
          bash ./sh/env/init.sh ${{ inputs.ENVIRONMENT_TYPE }}

      - name: Install Composer Dependencies
        run: |
          export CURRENT_UID=$(id -u)
          export CURRENT_GID=$(id -g)
          bash ./sh/install.sh yes

      - name: Cache dependencies theme - restore
        id: cache-deps-restore-theme
        uses: actions/cache/restore@v4
        with:
          path: |
            web/wp-content/themes/starter-kit-theme/node_modules
          key: build-cache-theme-${{ inputs.SSH_HOST_ALIAS }}-${{ runner.os }}

      - name: Install Node Dependencies
        run: |
          export CURRENT_UID=$(id -u)
          export CURRENT_GID=$(id -g)
          bash ./sh/install-node.sh yes

      - name: Cache dependencies - save
        if: steps.cache-deps-restore.outputs.cache-hit != 'true' || steps.cache-deps-restore-wis-blocks.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            vendor
          key: build-cache-${{ inputs.SSH_HOST_ALIAS }}-${{ runner.os }}

      - name: Cache dependencies - save
        if: steps.cache-deps-restore-theme.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            web/wp-content/themes/starter-kit-theme/node_modules
          key: build-cache-theme-${{ inputs.SSH_HOST_ALIAS }}-${{ runner.os }}

      - name: Save Built job
        uses: actions/cache/save@v4
        with:
          path: .
          key: build-job-${{ github.run_number }}

  deploy:
    runs-on: ubuntu-22.04

    needs: [ build ]

    steps:
      - name: Use Built job
        uses: actions/cache/restore@v4
        with:
          path: .
          key: build-job-${{ github.run_number }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo '${{ secrets.SSH_CONFIG }}' > ~/.ssh/config

      - name: Deploy via SSH
        run: |
          echo "Deploying to ${{ inputs.DEPLOY_PATH_DESTINATION }}"
          ssh ${{ inputs.SSH_HOST_ALIAS }} mkdir -p ${{ inputs.DEPLOY_PATH_DESTINATION }}
          rsync -og \
            --chmod=Dug=rwx,Fug=rw \
            --checksum \
            --recursive \
            --verbose \
            --compress \
            --links \
            --delete-after \
            --exclude ".git*" \
            --exclude "*/node_modules/" \
            --exclude "backups/" \
            --exclude "db-data/" \
            --exclude "logs/*" \
            --exclude "iac/" \
            --exclude ".env" \
            --exclude ".env.*override" \
            --exclude ".env.*secret" \
            --exclude "config/ssl/*/" \
            --exclude "web/wp-content/languages" \
            --exclude "web/wp-content/uploads" \
            --include "web/wp-content/cache" \
            ./ ${{ inputs.SSH_HOST_ALIAS }}:${{ inputs.DEPLOY_PATH_DESTINATION }}
          ssh ${{ inputs.SSH_HOST_ALIAS }} " \
            cd ${{ inputs.DEPLOY_PATH_DESTINATION }} && \
            make secret && \
            make recreate ${{ inputs.ENVIRONMENT_TYPE }}"
