name: Develop Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  deploy-to-dev:
    uses: ./.github/workflows/job-deploy.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_CONFIG: ${{ secrets.SSH_CONFIG_DEV }}
    with:
      SSH_ALIAS: ssh_alias
      DEPLOY_PATH_DESTINATION: /srv/develop.starter-kit.io
      WP_DEFAULT_THEME: starter-kit-theme
      DEPLOYMENT_NAME: "StarterKit push to develop"
      TYPE: dev
