name: Production Deploy

on:
  workflow_dispatch: {}

jobs:
  deploy-to-prod:
    uses: ./.github/workflows/job-deploy.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_CONFIG: ${{ secrets.SSH_CONFIG_PROD }}
    with:
      SSH_ALIAS: ssh_alias
      DEPLOY_PATH_DESTINATION: /srv/starter-kit.io
      DEPLOYMENT_NAME: "StarterKit push to production"
      ENVIRONMENT_TYPE: prod
